name: Test Postgres
on:
    push:
        branches:
            - main 
            - 'feature/**'
jobs:
    Valid-Postgres:
        runs-on: ubuntu-latest
        services:
            postgress-service:
                image: postgres:18-alpine3.23
                env:
                    POSTGRES_USER: ${{ secrets.POSTGRES_USERNAME }} 
                    POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
                    POSTGRES_DB: pro_test_db
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        steps:
            # Step 1: Pull down the repository code files onto the runner machine
            - name: Upload repo 
              uses: actions/checkout@v6
            # Step 2: Install the native lightweight client tool on the runner machine
            - name: Install PostgreSQL Client Utility
              run: |
                sudo apt-get update
                sudo apt-get install -y postgresql-client
            ## execut some query to postgres db
            - name: Run Database Smoke Test
              env:
                PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
              run: |
                echo "Executing pg_isready smoke test..."
                pg_isready -h localhost -p 5432 -U ${{ secrets.POSTGRES_USERNAME }}

            - name: Execute Non-Interactive SQL Tests
              env:
                PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD}}
              run: |
                echo "Connecting to containerized PostgreSQL service..."
                #  We pass the local .sql file straight into the container service running on localhost
                psql -h localhost -U ${{ secrets.POSTGRES_USERNAME}} -d pro_test_db -f scripts/test-2.sql

            - name: Extract Cell Value Verification
              env:
                PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD}}
              run: |
                # Fetch only the raw value of the execution status cell for the second test row
                TARGET_CELL=$(psql -h localhost -U runner_admin -d pro_test_db -t -c "SELECT username FROM users WHERE id = 1;" | tr -d ' ')
                echo "Extracted cell verification status is: $TARGET_CELL"
                if [ "$TARGET_CELL" = "cloud_engineer" ]; then
                   echo "[PASS]: Database integration verified successfully!"
                else
                   echo "[Faild]: Verification failed. Unexpected cell value."
                exit 1
                fi
            - name: CHECK CRUD
              env:
                PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD}}
              run: |
                # Fetch the 'UPDATE_LOGIC_TEST' from automated_test_logs
                CRUD=$(psql -h localhost -U runner_admin -d pro_test_db -t -c "SELECT test_result FROM automated_test_logs WHERE test_name = 'UPDATE_LOGIC_TEST';" | tr -d ' ')
                echo "Extracted cell verification status is: $TARGET_CELL"
                if [ "$CRUD" = "PASS" ]; then
                   echo "[PASS]: Database integration verified successfully!"
                else
                   echo "[Faild]: Verification failed. Unexpected cell value."
                exit 1
                fi
            - name: CHECK UNIQENES
              env:
                 PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD}}
              run: |
                # Fetch the 'CONSTRAINT_TEST' schema constraint from automated_test_logs
                UNIQ=$(psql -h localhost -U runner_admin -d pro_test_db -t -c "SELECT test_result FROM automated_test_logs WHERE test_name = 'CONSTRAINT_TEST';" | tr -d ' ')
                echo "Extracted cell verification status is: $TARGET_CELL"
                if [ "$UNIQ" = "PASS" ]; then
                   echo "[PASS]: Database Constraint verified successfully!"
                else
                   echo "[ Faild ]: Constraint failed. Unexpected cell value."
                exit 1
                fi

            
        